# Generated by Django 2.0.6 on 2018-08-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20180807_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='family',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='life.Family'),
        ),
    ]
