# Generated by Django 2.0.6 on 2018-08-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='qtype',
        ),
    ]
